# Generated by Django 2.2.7 on 2020-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(default=True),
        ),
    ]
