# Generated by Django 2.2.7 on 2020-06-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_testimonial_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimony',
            new_name='occupation',
        ),
    ]
