# Generated by Django 2.2.7 on 2020-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200630_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
    ]
