# Generated by Django 2.2.7 on 2020-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_testimonial_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('cityofdeparture', models.CharField(max_length=70)),
                ('incoterms', models.CharField(max_length=70)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('freight', models.CharField(choices=[('Less Than Truckload', 'Less Than Truckload'), ('Truckload', 'Truckload'), ('Intermodal', 'Intermodal'), ('Expedited', 'Expedited')], max_length=10)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
