# Generated by Django 2.2.7 on 2020-07-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='height',
            new_name='height_m',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='length',
            new_name='length_m',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='weight',
            new_name='weight_kg',
        ),
    ]
